version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  reviewers:
  - r-k-b
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  reviewers:
  - r-k-b
- package-ecosystem: cargo
  directory: "/backend"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  reviewers:
  - r-k-b
- package-ecosystem: elm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  reviewers:
  - r-k-b
