version: 1
update_configs:
  - package_manager: "rust:cargo"
    directory: "/src/fetcher/"
    update_schedule: "live"
    default_reviewers:
      - "r-k-b"

  - package_manager: "elm"
    directory: "/frontend/"
    update_schedule: "daily"
    default_reviewers:
      - "r-k-b"

#  - package_manager: "elm"
#    directory: "/frontend/review/"
#    update_schedule: "daily"
#    default_reviewers:
#      - "r-k-b"

#  - package_manager: "docker-compose" # ???  https://github.com/dependabot/feedback/issues/82
#    directory: "/"
#    update_schedule: "daily"
#    default_reviewers:
#      - "r-k-b"

