on: push
jobs:
  make:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: [ '13' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2.1.3
        name: cache elm
        with:
          path: ~/.elm
          key: ${{ runner.os }}-elm-${{ hashFiles('**/elm.json') }}
          restore-keys: |
            ${{ runner.os }}-elm-

      - uses: actions/cache@v2.1.3
        name: cache npm (frontend)
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache cargo registry
        uses: actions/cache@v2.1.3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v2.1.3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v2.1.3
        with:
          path: backend/target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('backend/Cargo.lock') }}

      - name: build fetcher
        uses: actions-rs/cargo@v1
        with:
          command: build
          # `working-directory` not supported; https://github.com/actions-rs/cargo/issues/6
          args: --manifest-path backend/Cargo.toml --bin fetcher

      - name: test fetcher
        uses: actions-rs/cargo@v1
        with:
          command: test
          # `working-directory` not supported; https://github.com/actions-rs/cargo/issues/6
          args: --manifest-path backend/Cargo.toml --bin fetcher

      - name: build replenisher
        uses: actions-rs/cargo@v1
        with:
          command: build
          # `working-directory` not supported; https://github.com/actions-rs/cargo/issues/6
          args: --manifest-path backend/Cargo.toml --bin replenisher

      - name: test replenisher
        uses: actions-rs/cargo@v1
        with:
          command: test
          # `working-directory` not supported; https://github.com/actions-rs/cargo/issues/6
          args: --manifest-path backend/Cargo.toml --bin replenisher

      - name: Setup node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node }}

      - name: install frontend
        run: npm install
        working-directory: frontend

      - name: test frontend
        run: npm test
        working-directory: frontend

#      - name: Review
#        working-directory: frontend
#        run: npm run review
